[phases.setup]
nixPkgs = ["nodejs", "npm", "chromium"]

[phases.install]
cmds = ["npm install --omit=dev"]

[phases.build]
cmds = ["npm run build --if-present"]

[start]
cmd = "node index.js"

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"










